name: Execução dos testes unitários com Jest

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes
        run: npm run test